//! WH3 start-game option pack generation.
//!
//! This module owns the pure byte-level generation for the lightweight launch
//! option pack used by the legacy TypeScript app as `!!!!out.pack`. Filesystem
//! writes and launch-list placement stay in runtime/launcher adapters.

use std::path::Path;

use crate::db::{
    DbCell, DbFieldSchema, DbFieldType, DbPrimitiveValue, DbRows, read_db_rows_from_pack,
    write_db_rows_to_payload,
};
use crate::pack::{
    PackFileKind, PackFileMetadata, PackFileWrite, PackReadOptions, build_pfh5_pack_bytes,
    read_pack_index, read_packed_file_metadata,
};
use crate::ports::{CoreError, CoreResult};
use crate::schema::{DbSchema, DbVersionSchema, resolve_table_schema};

/// Generated start-game pack file name used by the TS implementation.
pub const WH3_START_GAME_PACK_NAME: &str = "!!!!out.pack";
/// DB folder name used by WH3 battle permission tables.
pub const WH3_BATTLE_PERMISSIONS_DB_NAME: &str = "units_custom_battle_permissions_tables";
/// Packed DB table path generated by the TS `MakeUnitsGenerals` option.
pub const WH3_MAKE_UNITS_GENERALS_TABLE_PATH: &str =
    "db\\units_custom_battle_permissions_tables\\!!!!whmm_out";
/// Stable GUID used by the TS-generated battle-permission table.
pub const WH3_MAKE_UNITS_GENERALS_TABLE_GUID: &str = "129d32d8-3563-4d4f-8e19-a815e834e456";
/// DB version written by the TS-generated battle-permission table.
pub const WH3_MAKE_UNITS_GENERALS_TABLE_VERSION: i32 = 11;
/// WH3 vanilla data packs the TS implementation includes as start-game source
/// data when building generated `!!!!out.pack` options.
pub const WH3_START_GAME_SOURCE_PACK_NAMES: [&str; 3] =
    ["data.pack", "db.pack", "data_script.pack"];

/// Options supported by the Rust start-game pack generator.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
#[allow(clippy::struct_excessive_bools)]
pub struct Wh3StartGamePackOptions {
    /// Make units available as custom-battle generals.
    ///
    /// This TS option rewrites `units_custom_battle_permissions_tables` rows.
    /// Use `build_wh3_start_game_pack_with_battle_permissions(...)` when
    /// source rows are available.
    pub make_units_generals: bool,
    /// Replace WH3 intro movie files with a minimal blank movie payload.
    pub skip_intro_movies: bool,
    /// Enable game script console logging.
    pub script_logging: bool,
    /// Auto-click through frontend custom battle startup for testing.
    pub auto_start_custom_battle: bool,
}

/// Generated pack bytes and indexed file names.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedStartGamePack {
    /// Pack file name.
    pub pack_name: String,
    /// Complete `.pack` bytes.
    pub bytes: Vec<u8>,
    /// Packed file names written into the pack index.
    pub packed_file_names: Vec<String>,
}

/// Decoded enabled battle-permission tables plus the schema selected for them.
#[derive(Clone, Debug, PartialEq)]
pub struct Wh3BattlePermissionTables {
    /// Shared schema selected for decoded rows, if any table was found.
    pub schema: Option<DbVersionSchema>,
    /// Decoded DB rows in pack/index order.
    pub tables: Vec<DbRows>,
}

/// Builds WH3's `!!!!out.pack` for supported start-game options.
///
/// Returns `Ok(None)` when no supported options are enabled.
///
/// # Errors
///
/// Returns [`CoreError`] when generated sizes cannot fit the WH3 pack index
/// integer fields.
pub fn build_wh3_start_game_pack(
    options: &Wh3StartGamePackOptions,
) -> CoreResult<Option<GeneratedStartGamePack>> {
    if options.make_units_generals {
        return Err(CoreError::invalid_input(
            "MakeUnitsGenerals requires DB table rewriting and enabled battle-permission DB rows; use build_wh3_start_game_pack_with_battle_permissions",
        ));
    }

    let files = wh3_start_game_pack_files(options);
    if files.is_empty() {
        return Ok(None);
    }

    let packed_file_names = files.iter().map(|file| file.name.clone()).collect();
    Ok(Some(GeneratedStartGamePack {
        pack_name: WH3_START_GAME_PACK_NAME.to_string(),
        bytes: build_pfh5_pack_bytes(&files)?,
        packed_file_names,
    }))
}

/// Reads enabled WH3 battle-permission DB tables from pack paths.
///
/// # Errors
///
/// Returns [`CoreError`] when a pack cannot be read, a matching DB table cannot
/// be decoded, the schema cannot be resolved, or matching tables use
/// incompatible schemas.
pub fn read_wh3_battle_permission_tables_from_packs<P>(
    pack_paths: &[P],
    schema: &DbSchema,
) -> CoreResult<Wh3BattlePermissionTables>
where
    P: AsRef<Path>,
{
    let mut selected_schema = None::<DbVersionSchema>;
    let mut tables = Vec::new();

    for pack_path in pack_paths {
        let pack_path = pack_path.as_ref();
        let index = read_pack_index(pack_path, &PackReadOptions::default())?;
        for entry in &index.files {
            let PackFileKind::DbTable { db_name, .. } = entry.kind() else {
                continue;
            };
            if db_name != WH3_BATTLE_PERMISSIONS_DB_NAME {
                continue;
            }

            let metadata = read_packed_file_metadata(pack_path, entry)?;
            let PackFileMetadata::DbTable(metadata) = metadata else {
                continue;
            };
            let table_schema = resolve_table_schema(schema, &metadata).ok_or_else(|| {
                CoreError::parse(format!(
                    "could not resolve schema for {} version {:?}",
                    metadata.name, metadata.version
                ))
            })?;

            if let Some(existing_schema) = &selected_schema {
                if existing_schema.fields != table_schema.fields {
                    return Err(CoreError::parse(format!(
                        "incompatible battle-permission schema versions: {} and {}",
                        existing_schema.version, table_schema.version
                    )));
                }
            } else {
                selected_schema = Some(table_schema.clone());
            }

            tables.push(read_db_rows_from_pack(
                pack_path,
                entry,
                &table_schema.fields,
            )?);
        }
    }

    Ok(Wh3BattlePermissionTables {
        schema: selected_schema,
        tables,
    })
}

/// Builds WH3's `!!!!out.pack`, including `MakeUnitsGenerals` DB table output
/// when battle-permission source rows are supplied.
///
/// # Errors
///
/// Returns [`CoreError`] when generated pack sizes cannot fit WH3 pack fields,
/// `MakeUnitsGenerals` is enabled without source rows, or supplied DB rows
/// cannot be transformed/serialized with the supplied schema.
pub fn build_wh3_start_game_pack_with_battle_permissions(
    options: &Wh3StartGamePackOptions,
    battle_permission_tables: &[DbRows],
    battle_permission_schema: &[DbFieldSchema],
) -> CoreResult<Option<GeneratedStartGamePack>> {
    let mut files = Vec::new();

    if options.make_units_generals {
        files.push(PackFileWrite {
            name: WH3_MAKE_UNITS_GENERALS_TABLE_PATH.to_string(),
            payload: build_wh3_make_units_generals_payload(
                battle_permission_tables,
                battle_permission_schema,
            )?,
        });
    }
    files.extend(wh3_start_game_pack_files(options));

    if files.is_empty() {
        return Ok(None);
    }

    let packed_file_names = files.iter().map(|file| file.name.clone()).collect();
    Ok(Some(GeneratedStartGamePack {
        pack_name: WH3_START_GAME_PACK_NAME.to_string(),
        bytes: build_pfh5_pack_bytes(&files)?,
        packed_file_names,
    }))
}

/// Builds the generated `MakeUnitsGenerals` DB table payload from enabled
/// `units_custom_battle_permissions_tables` rows.
///
/// # Errors
///
/// Returns [`CoreError`] when no source rows are supplied, the schema does not
/// contain a Boolean `general_unit` field, or row serialization fails.
pub fn build_wh3_make_units_generals_payload(
    battle_permission_tables: &[DbRows],
    battle_permission_schema: &[DbFieldSchema],
) -> CoreResult<Vec<u8>> {
    let rows =
        build_wh3_make_units_generals_rows(battle_permission_tables, battle_permission_schema)?;
    write_db_rows_to_payload(&rows, battle_permission_schema)
}

/// Builds the generated `MakeUnitsGenerals` DB rows from enabled
/// `units_custom_battle_permissions_tables` rows.
///
/// # Errors
///
/// Returns [`CoreError`] when no source rows are supplied or the schema/rows do
/// not contain a Boolean `general_unit` field.
pub fn build_wh3_make_units_generals_rows(
    battle_permission_tables: &[DbRows],
    battle_permission_schema: &[DbFieldSchema],
) -> CoreResult<DbRows> {
    if battle_permission_tables.is_empty() {
        return Err(CoreError::invalid_input(
            "MakeUnitsGenerals requires at least one battle-permission DB table",
        ));
    }

    let general_unit_index = battle_permission_schema
        .iter()
        .position(|field| field.name == "general_unit")
        .ok_or_else(|| {
            CoreError::invalid_input("MakeUnitsGenerals schema is missing the general_unit field")
        })?;
    let general_unit_field = &battle_permission_schema[general_unit_index];
    if general_unit_field.field_type != DbFieldType::Boolean {
        return Err(CoreError::invalid_input(
            "MakeUnitsGenerals general_unit field must be Boolean",
        ));
    }

    let mut generated_rows = Vec::new();
    for (table_index, table) in battle_permission_tables.iter().enumerate() {
        let mut table_rows = Vec::with_capacity(table.rows.len());
        let mut duplicated_general_rows = Vec::new();
        for (row_index, row) in table.rows.iter().enumerate() {
            if row.len() != battle_permission_schema.len() {
                return Err(CoreError::invalid_input(format!(
                    "battle-permission table {table_index} row {row_index} has {} cells but schema has {} fields",
                    row.len(),
                    battle_permission_schema.len()
                )));
            }

            let mut transformed = row.clone();
            ensure_row_cell_names(
                table_index,
                row_index,
                &transformed,
                battle_permission_schema,
            )?;
            let general_unit = match &transformed[general_unit_index].value {
                DbPrimitiveValue::Boolean(value) => *value,
                _ => {
                    return Err(CoreError::invalid_input(format!(
                        "battle-permission table {table_index} row {row_index} general_unit value is not Boolean"
                    )));
                }
            };

            if general_unit == 1 {
                let mut duplicate = transformed.clone();
                duplicate[general_unit_index].value = DbPrimitiveValue::Boolean(0);
                duplicated_general_rows.push(duplicate);
            } else {
                transformed[general_unit_index].value = DbPrimitiveValue::Boolean(1);
            }
            table_rows.push(transformed);
        }

        table_rows.extend(duplicated_general_rows);
        generated_rows.extend(table_rows);
    }

    Ok(DbRows {
        guid: Some(WH3_MAKE_UNITS_GENERALS_TABLE_GUID.to_string()),
        version: Some(WH3_MAKE_UNITS_GENERALS_TABLE_VERSION),
        rows: generated_rows,
    })
}

fn wh3_start_game_pack_files(options: &Wh3StartGamePackOptions) -> Vec<PackFileWrite> {
    let mut files = Vec::new();

    if options.skip_intro_movies {
        files.extend(WH3_INTRO_MOVIES.iter().map(|name| PackFileWrite {
            name: (*name).to_string(),
            payload: EMPTY_MOVIE.to_vec(),
        }));
    }
    if options.script_logging {
        files.push(PackFileWrite {
            name: "script\\enable_console_logging".to_string(),
            payload: vec![0x00],
        });
    }
    if options.auto_start_custom_battle {
        files.push(PackFileWrite {
            name: "script\\frontend\\mod\\pj_auto_custom_battles.lua".to_string(),
            payload: AUTO_START_CUSTOM_BATTLE_SCRIPT.as_bytes().to_vec(),
        });
    }

    files
}
fn ensure_row_cell_names(
    table_index: usize,
    row_index: usize,
    row: &[DbCell],
    schema: &[DbFieldSchema],
) -> CoreResult<()> {
    for (field, cell) in schema.iter().zip(row) {
        if cell.name != field.name {
            return Err(CoreError::invalid_input(format!(
                "battle-permission table {table_index} row {row_index} expected field {} but found {}",
                field.name, cell.name
            )));
        }
    }

    Ok(())
}

const WH3_INTRO_MOVIES: [&str; 6] = [
    "movies\\epilepsy_warning\\epilepsy_warning_en.ca_vp8",
    "movies\\gam_int.ca_vp8",
    "movies\\startup_movie_01.ca_vp8",
    "movies\\startup_movie_02.ca_vp8",
    "movies\\startup_movie_03.ca_vp8",
    "movies\\startup_movie_04.ca_vp8",
];

const EMPTY_MOVIE: &[u8] = &[
    0x43, 0x41, 0x4d, 0x56, 0x01, 0x00, 0x29, 0x00, 0x56, 0x50, 0x38, 0x30, 0x80, 0x02, 0xe0, 0x01,
    0x55, 0x55, 0x85, 0x42, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x4a, 0x02, 0x00, 0x00,
    0x01, 0x00, 0x00, 0x00, 0x21, 0x02, 0x00, 0x00, 0x00, 0x50, 0x42, 0x00, 0x9d, 0x01, 0x2a, 0x80,
    0x02, 0xe0, 0x01, 0x00, 0x47, 0x08, 0x85, 0x85, 0x88, 0x85, 0x84, 0x88, 0x02, 0x02, 0x00, 0x06,
    0x16, 0x04, 0xf7, 0x06, 0x81, 0x64, 0x9f, 0x6b, 0xdb, 0x9b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b,
    0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27,
    0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38,
    0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b,
    0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27,
    0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38,
    0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b,
    0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27,
    0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38,
    0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b,
    0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27,
    0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38,
    0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b,
    0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27,
    0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38,
    0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b,
    0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27,
    0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38,
    0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b,
    0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27,
    0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38,
    0x7b, 0x27, 0x38, 0x7b, 0x27, 0x38, 0x7b, 0x27, 0x37, 0x80, 0xfe, 0xff, 0xab, 0x50, 0x80, 0x29,
    0x00, 0x00, 0x00, 0x21, 0x02, 0x00, 0x00, 0x01,
];

const AUTO_START_CUSTOM_BATTLE_SCRIPT: &str = r#"core:remove_listener("pj_auto_custom_battles_FrontendScreenTransition")
core:add_listener(
	"pj_auto_custom_battles_FrontendScreenTransition",
	"FrontendScreenTransition",
	function(context)
		return context.string == "custom_battle"
	end,
	function(context)
		core:remove_listener("pj_auto_custom_battles_press_factions_button")
		core:add_listener(
			"pj_auto_custom_battles_press_factions_button",
			"RealTimeTrigger",
			function(context)
				return context.string == "pj_auto_custom_battles_press_factions_button"
			end,
			function(context)
					local start_battle = find_uicomponent(core:get_ui_root(), "custom_battle", "ready_parent", "start_button_frame", "button_start_battle")
					start_battle:SimulateLClick()
			end,
			false
		)

		real_timer.register_singleshot("pj_auto_custom_battles_press_factions_button", 1000)
	end,
	true
)

local function run_it()
    local battle_button = find_uicomponent(core:get_ui_root(), "main", "left_holder", "buttons_holder", "buttons_list", "battle_frame", "battle_buttons", "practice_battle_holder", "button_practice_battle")
    if battle_button then
        battle_button:SimulateLClick()
    end
end

core:add_ui_created_callback(
	function()
		run_it()
	end
)
"#;

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;
    use std::fs;
    use std::sync::atomic::{AtomicU64, Ordering};

    use super::{
        WH3_MAKE_UNITS_GENERALS_TABLE_GUID, WH3_MAKE_UNITS_GENERALS_TABLE_PATH,
        WH3_MAKE_UNITS_GENERALS_TABLE_VERSION, Wh3StartGamePackOptions,
        build_wh3_make_units_generals_rows, build_wh3_start_game_pack,
        build_wh3_start_game_pack_with_battle_permissions,
    };
    use crate::ports::CoreErrorKind;
    use crate::{
        DbCell, DbFieldSchema, DbFieldType, DbPrimitiveValue, DbRows, PackFileMetadata,
        PackReadOptions, WH3_BATTLE_PERMISSIONS_DB_NAME, read_db_rows_from_pack, read_pack_index,
        read_packed_file_metadata, read_packed_file_payload,
    };

    static TEST_FILE_COUNTER: AtomicU64 = AtomicU64::new(0);

    #[test]
    fn returns_none_when_no_supported_options_are_enabled() {
        assert_eq!(
            build_wh3_start_game_pack(&Wh3StartGamePackOptions::default()).unwrap(),
            None
        );
    }

    #[test]
    fn builds_wh3_start_game_pack_for_raw_payload_options() {
        let generated = build_wh3_start_game_pack(&Wh3StartGamePackOptions {
            skip_intro_movies: true,
            script_logging: true,
            auto_start_custom_battle: true,
            ..Wh3StartGamePackOptions::default()
        })
        .unwrap()
        .unwrap();
        let path = write_temp_pack("start-game-options", &generated.bytes);

        let index = read_pack_index(&path, &PackReadOptions::default()).unwrap();

        assert_eq!(generated.pack_name, "!!!!out.pack");
        assert_eq!(index.magic, *b"PFH5");
        assert_eq!(index.byte_mask, 3);
        assert_eq!(index.files.len(), 8);
        assert_eq!(
            index.files[0].name,
            "movies\\epilepsy_warning\\epilepsy_warning_en.ca_vp8"
        );
        assert_eq!(index.files[6].name, "script\\enable_console_logging");
        assert_eq!(
            index.files[7].name,
            "script\\frontend\\mod\\pj_auto_custom_battles.lua"
        );

        let script_logging_payload = read_packed_file_payload(&path, &index.files[6]).unwrap();
        let auto_battle_payload = read_packed_file_payload(&path, &index.files[7]).unwrap();
        assert_eq!(script_logging_payload, [0x00]);
        assert!(
            String::from_utf8(auto_battle_payload)
                .unwrap()
                .contains("pj_auto_custom_battles_FrontendScreenTransition")
        );

        fs::remove_file(path).ok();
    }

    #[test]
    fn raw_start_game_pack_rejects_make_units_generals_without_source_tables() {
        let error = build_wh3_start_game_pack(&Wh3StartGamePackOptions {
            make_units_generals: true,
            script_logging: true,
            ..Wh3StartGamePackOptions::default()
        })
        .unwrap_err();

        assert_eq!(error.kind, CoreErrorKind::InvalidInput);
        assert!(error.message.contains("MakeUnitsGenerals"));
        assert!(error.message.contains("DB table rewriting"));
    }

    #[test]
    fn builds_make_units_generals_rows_like_ts() {
        let schema = battle_permission_schema();
        let source = DbRows {
            guid: None,
            version: Some(11),
            rows: vec![
                battle_permission_row(
                    "wh3_main_cth_cathay",
                    0,
                    "wh3_main_cth_inf_peasant_spearmen_0",
                ),
                battle_permission_row("wh3_main_kho_khorne", 1, "wh3_main_kho_cha_skarbrand_0"),
            ],
        };

        let generated = build_wh3_make_units_generals_rows(&[source], &schema).unwrap();

        assert_eq!(
            generated.guid,
            Some(WH3_MAKE_UNITS_GENERALS_TABLE_GUID.to_string())
        );
        assert_eq!(
            generated.version,
            Some(WH3_MAKE_UNITS_GENERALS_TABLE_VERSION)
        );
        assert_eq!(generated.rows.len(), 3);
        assert_eq!(general_unit(&generated.rows[0]), 1);
        assert_eq!(general_unit(&generated.rows[1]), 1);
        assert_eq!(general_unit(&generated.rows[2]), 0);
        assert_eq!(unit_key(&generated.rows[2]), "wh3_main_kho_cha_skarbrand_0");
    }

    #[test]
    fn builds_start_game_pack_with_make_units_generals_db_payload() {
        let schema = battle_permission_schema();
        let source = DbRows {
            guid: None,
            version: Some(11),
            rows: vec![
                battle_permission_row(
                    "wh3_main_cth_cathay",
                    0,
                    "wh3_main_cth_inf_peasant_spearmen_0",
                ),
                battle_permission_row("wh3_main_kho_khorne", 1, "wh3_main_kho_cha_skarbrand_0"),
            ],
        };
        let generated = build_wh3_start_game_pack_with_battle_permissions(
            &Wh3StartGamePackOptions {
                make_units_generals: true,
                script_logging: true,
                ..Wh3StartGamePackOptions::default()
            },
            &[source],
            &schema,
        )
        .unwrap()
        .unwrap();
        let path = write_temp_pack("start-game-make-units-generals", &generated.bytes);

        let index = read_pack_index(&path, &PackReadOptions::default()).unwrap();

        assert_eq!(index.files.len(), 2);
        assert_eq!(index.files[0].name, WH3_MAKE_UNITS_GENERALS_TABLE_PATH);
        assert_eq!(index.files[1].name, "script\\enable_console_logging");

        let metadata = read_packed_file_metadata(&path, &index.files[0]).unwrap();
        let PackFileMetadata::DbTable(metadata) = metadata else {
            panic!("expected generated DB table metadata");
        };
        assert_eq!(
            metadata.guid,
            Some(WH3_MAKE_UNITS_GENERALS_TABLE_GUID.to_string())
        );
        assert_eq!(
            metadata.version,
            Some(WH3_MAKE_UNITS_GENERALS_TABLE_VERSION)
        );
        assert_eq!(metadata.entry_count, 3);

        let rows = read_db_rows_from_pack(&path, &index.files[0], &schema).unwrap();
        assert_eq!(rows.rows.len(), 3);
        assert_eq!(general_unit(&rows.rows[0]), 1);
        assert_eq!(general_unit(&rows.rows[1]), 1);
        assert_eq!(general_unit(&rows.rows[2]), 0);

        fs::remove_file(path).ok();
    }

    #[test]
    fn reads_battle_permission_tables_from_pack_paths() {
        let schema = battle_permission_schema();
        let source = DbRows {
            guid: None,
            version: Some(11),
            rows: vec![battle_permission_row(
                "wh3_main_cth_cathay",
                0,
                "wh3_main_cth_inf_peasant_spearmen_0",
            )],
        };
        let generated = build_wh3_start_game_pack_with_battle_permissions(
            &Wh3StartGamePackOptions {
                make_units_generals: true,
                ..Wh3StartGamePackOptions::default()
            },
            &[source],
            &schema,
        )
        .unwrap()
        .unwrap();
        let path = write_temp_pack("read-battle-permission-tables", &generated.bytes);

        let collected = super::read_wh3_battle_permission_tables_from_packs(
            &[path.clone()],
            &battle_permission_schema_map(schema),
        )
        .unwrap();

        assert_eq!(collected.schema.as_ref().unwrap().version, 11);
        assert_eq!(collected.tables.len(), 1);
        assert_eq!(collected.tables[0].rows.len(), 1);
        assert_eq!(general_unit(&collected.tables[0].rows[0]), 1);

        fs::remove_file(path).ok();
    }

    fn write_temp_pack(test_name: &str, bytes: &[u8]) -> std::path::PathBuf {
        let counter = TEST_FILE_COUNTER.fetch_add(1, Ordering::Relaxed);
        let mut path = std::env::temp_dir();
        path.push(format!(
            "wh3mm-core-{test_name}-{}-{counter}.pack",
            std::process::id()
        ));
        fs::write(&path, bytes).unwrap();
        path
    }

    fn battle_permission_schema() -> Vec<DbFieldSchema> {
        vec![
            field("faction", DbFieldType::StringU8, true),
            field("general_unit", DbFieldType::Boolean, true),
            field("unit", DbFieldType::StringU8, true),
            field("siege_unit_attacker", DbFieldType::Boolean, false),
            field("siege_unit_defender", DbFieldType::Boolean, false),
            field("general_portrait", DbFieldType::OptionalStringU8, false),
            field("general_uniform", DbFieldType::OptionalStringU8, false),
            field("set_piece_character", DbFieldType::OptionalStringU8, false),
            field("campaign_exclusive", DbFieldType::Boolean, false),
            field("armory_item_set", DbFieldType::OptionalStringU8, false),
        ]
    }

    fn battle_permission_schema_map(schema: Vec<DbFieldSchema>) -> crate::DbSchema {
        let mut schema_map = BTreeMap::new();
        schema_map.insert(
            WH3_BATTLE_PERMISSIONS_DB_NAME.to_string(),
            vec![crate::DbVersionSchema {
                version: 11,
                fields: schema,
            }],
        );
        schema_map
    }

    fn battle_permission_row(faction: &str, general_unit: u8, unit: &str) -> Vec<DbCell> {
        vec![
            cell(
                "faction",
                DbPrimitiveValue::String(faction.to_string()),
                true,
            ),
            cell(
                "general_unit",
                DbPrimitiveValue::Boolean(general_unit),
                true,
            ),
            cell("unit", DbPrimitiveValue::String(unit.to_string()), true),
            cell("siege_unit_attacker", DbPrimitiveValue::Boolean(1), false),
            cell("siege_unit_defender", DbPrimitiveValue::Boolean(1), false),
            cell(
                "general_portrait",
                DbPrimitiveValue::OptionalString(None),
                false,
            ),
            cell(
                "general_uniform",
                DbPrimitiveValue::OptionalString(None),
                false,
            ),
            cell(
                "set_piece_character",
                DbPrimitiveValue::OptionalString(None),
                false,
            ),
            cell("campaign_exclusive", DbPrimitiveValue::Boolean(0), false),
            cell(
                "armory_item_set",
                DbPrimitiveValue::OptionalString(None),
                false,
            ),
        ]
    }

    fn field(name: &str, field_type: DbFieldType, is_key: bool) -> DbFieldSchema {
        DbFieldSchema {
            name: name.to_string(),
            field_type,
            is_key,
            reference: None,
        }
    }

    fn cell(name: &str, value: DbPrimitiveValue, is_key: bool) -> DbCell {
        DbCell {
            name: name.to_string(),
            is_key,
            value,
        }
    }

    fn general_unit(row: &[DbCell]) -> u8 {
        let DbPrimitiveValue::Boolean(value) = &row[1].value else {
            panic!("expected general_unit Boolean");
        };
        *value
    }

    fn unit_key(row: &[DbCell]) -> &str {
        let DbPrimitiveValue::String(value) = &row[2].value else {
            panic!("expected unit StringU8");
        };
        value
    }
}
